- name: creating EC2 instance
  hosts: local
  connection: local
  vars:
    AMI_ID: "ami-0220d79f3f480ecf5"
    SG_ID: "sg-03dde207ea3271219"
    INS_TYPE: "t3.micro"
  tasks:
    - name: create EC2
      amazon.aws.ec2_instance:
        name: "{{ item }}"
        security_group: "{{ SG_ID }}"
        image_id: "{{ AMI_ID }}"
        instance_type: "{{ INS_TYPE }}"
      loop:
        - catalogue
        - user
      register: output_EC2
    - name: print output_EC2
      ansible.builtin.debug:
        msg: "{{ output_EC2 }}"
    
        
      
      