[local]
localhost

[mongodb]
monogodb-dev.anildevops.online

[catalogue]
catalogue-dev.anildevops.online

[user]
user-dev.anildevops.online

[redis]
redis-dev.anildevops.online

[cart]
cart-dev.anildevops.online

[shipping]
shipping-dev.anildevops.online

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321