[local]
localhost

[mongodb]
mongodb-dev.anildevops.online

[catalogue]
catalogue-dev.anildevops.online

[user]
user-dev.anildevops.online

[redis]
redis-dev.anildevops.online

[cart]
cart-dev.anildevops.online

[mysql]
mysql-dev.anildevops.online

[shipping]
shipping-dev.anildevops.online

[frontend]
frontend-dev.anildevops.online

[rabbitmq]
rabbitmq-dev.anildevops.online

[payment]
payment-dev.anildevops.online

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321