- name: creating and installing mongodb
  hosts: mongodb
  become: yes
  tasks:
    - name: copying mongo repo
      ansible.builtin.copy:
        src: mongo.repo
        dest: "/etc/yum.repos.d/mongo.repo"
    - name: installing mongodb
      ansible.builtin.dnf:
        name: mongodb-org
        state: present
    - name: starting and enabling mongodb
      ansible.builtin.service:
        name: mongod
        state: started
        enabled: yes
    - name: allowing remote connections
      ansible.builtin.replace:
        path: /etc/mongod.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'
    - name: starting and enabling mongodb
      ansible.builtin.service:
        name: mongod
        state: restarted
